function previousTrace = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PREVIOUSTRACE = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  PREVIOUSTRACE = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  previousTrace = importfile("D:\Skola - magistr\druhák\MPC-AUP\projekt\project_AUP2\project_AUP\Trace\previousTrace.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 26-Nov-2023 18:31:49

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Sample", "Xms22112023221335738UTC", "DataTank1WaterTempAIScaled", "DataTank1HeaterStateHeatingOut"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
previousTrace = readtable(filename, opts);

%% Convert to output type
previousTrace = table2array(previousTrace);
end